# Generated by Django 3.0.3 on 2020-03-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='department',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='class_object',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='class_object',
            field=models.ManyToManyField(to='textbook_exchange.Class'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='class_object',
        ),
        migrations.AddField(
            model_name='textbook',
            name='class_object',
            field=models.ManyToManyField(to='textbook_exchange.Class'),
        ),
    ]
