# Generated by Django 3.0.3 on 2020-02-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
