# Generated by Django 3.0.3 on 2020-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_acronym',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='class_object',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='edition',
        ),
        migrations.AddField(
            model_name='class',
            name='class_info',
            field=models.TextField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='class',
            name='course_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='bookstore_new_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='bookstore_used_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='cover_photo_url',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='textbook',
            name='description',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='textbook',
            name='google_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='publisher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='textbook',
            name='req_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='class_key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='class_object',
        ),
        migrations.AddField(
            model_name='textbook',
            name='class_object',
            field=models.ManyToManyField(to='textbook_exchange.Class'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(default='', max_length=350),
        ),
    ]
