# Generated by Django 3.0.3 on 2020-04-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='picture',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='picture_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
