# Generated by Django 3.0.3 on 2020-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0002_productlisting_picture_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='cart',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='cart',
            field=models.ManyToManyField(blank=True, to='textbook_exchange.Cart'),
        ),
    ]
