# Generated by Django 3.0.3 on 2020-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0002_auto_20200321_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
