# Generated by Django 3.0.3 on 2020-04-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0002_auto_20200405_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='picture',
            field=models.BinaryField(default=b''),
        ),
    ]
