# Generated by Django 3.0.3 on 2020-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0002_auto_20200329_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='isbn',
            new_name='isbn13',
        ),
        migrations.AddField(
            model_name='textbook',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='textbook',
            name='isbn10',
            field=models.CharField(default='', max_length=200),
        ),
    ]
