# Generated by Django 3.0.3 on 2020-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0002_auto_20200405_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
