# Generated by Django 3.0.3 on 2020-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0002_auto_20200227_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=120, verbose_name='username'),
        ),
    ]
