# Generated by Django 3.0.3 on 2020-02-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0003_auto_20200227_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='class_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook_exchange.Class'),
        ),
    ]
