# Generated by Django 3.0.3 on 2020-03-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0003_auto_20200329_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='class_object',
            new_name='class_objects',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='class_key',
        ),
        migrations.AddField(
            model_name='class',
            name='class_term',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='professor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='section_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.RenameField(
            model_name='textbook',
            old_name='isbn13',
            new_name='bookstore_isbn',
        ),
        migrations.AddField(
            model_name='textbook',
            name='isbn13',
            field=models.CharField(default='', max_length=200),
        ),
    ]
