# Generated by Django 3.0.3 on 2020-03-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0003_auto_20200329_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
