# Generated by Django 3.0.3 on 2020-02-27 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0004_auto_20200226_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
