# Generated by Django 3.0.3 on 2020-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0004_auto_20200413_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='sold_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date sold'),
        ),
    ]
