# Generated by Django 3.0.3 on 2020-03-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0004_auto_20200330_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textbook_exchange.Cart'),
        ),
    ]
