# Generated by Django 3.0.3 on 2020-03-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0004_auto_20200322_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='dept',
            new_name='department',
        ),
    ]
