# Generated by Django 3.0.3 on 2020-02-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0005_listing_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_published',
        ),
    ]
