# Generated by Django 3.0.3 on 2020-03-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0005_auto_20200322_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_info',
            field=models.TextField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
