# Generated by Django 3.0.3 on 2020-03-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0005_auto_20200329_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
