# Generated by Django 3.0.3 on 2020-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0005_auto_20200330_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='edition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
