# Generated by Django 3.0.3 on 2020-03-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0006_productlisting_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='edition',
        ),
    ]
