# Generated by Django 3.0.3 on 2020-03-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0006_auto_20200329_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_code',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
