# Generated by Django 3.0.3 on 2020-03-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0006_auto_20200322_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='class_object',
        ),
    ]
