# Generated by Django 3.0.3 on 2020-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0007_remove_productlisting_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
