# Generated by Django 3.0.3 on 2020-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0007_remove_productlisting_class_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
