# Generated by Django 3.0.3 on 2020-03-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0007_auto_20200323_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook_exchange.Cart'),
        ),
    ]
