# Generated by Django 3.0.3 on 2020-02-27 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0008_auto_20200226_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='hasBeenSoldFlag',
            field=models.BooleanField(default=False),
        ),
    ]
