# Generated by Django 3.0.3 on 2020-03-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0009_auto_20200324_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textbook_exchange.Cart'),
        ),
    ]
