# Generated by Django 3.0.3 on 2020-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0009_auto_20200227_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition_choices',
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(default='acceptable', max_length=10),
            preserve_default=False,
        ),
    ]
