# Generated by Django 3.0.3 on 2020-02-27 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0010_auto_20200227_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.CharField(max_length=10)),
                ('picture', models.ImageField(upload_to='listing_images')),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('hasBeenSoldFlag', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook_exchange.Class')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook_exchange.Textbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
