# Generated by Django 3.0.3 on 2020-03-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0010_auto_20200324_1045'),
        ('textbook_exchange', '0008_auto_20200323_1937'),
    ]

    operations = [
    ]
