# Generated by Django 3.0.3 on 2020-04-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_exchange', '0017_auto_20200412_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
